/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { DocumentResponse } from '../models';
import { Perception } from '../models';
import { ValidationResponse } from '../models';
/**
 * PerceptionApi - axios parameter creator
 * @export
 */
export const PerceptionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retorna el XML
         * @summary Generar el XML de un Comprobante de Percepcion
         * @param {Perception} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPerceptionXml: async (body: Perception, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling getPerceptionXml.');
            }
            const localVarPath = `/peception/xml`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna el pdf
         * @summary Generar el pdf de un Comprobante de Percepcion
         * @param {Perception} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPerceptionpdf: async (body: Perception, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling getPerceptionpdf.');
            }
            const localVarPath = `/peception/pdf`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna la respuesta de SUNAT y el XML firmado
         * @summary Enviar un Comprobante de Percepcion
         * @param {Perception} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendPerception: async (body: Perception, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling sendPerception.');
            }
            const localVarPath = `/peception/send`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PerceptionApi - functional programming interface
 * @export
 */
export const PerceptionApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retorna el XML
         * @summary Generar el XML de un Comprobante de Percepcion
         * @param {Perception} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPerceptionXml(body: Perception, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await PerceptionApiAxiosParamCreator(configuration).getPerceptionXml(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retorna el pdf
         * @summary Generar el pdf de un Comprobante de Percepcion
         * @param {Perception} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPerceptionpdf(body: Perception, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await PerceptionApiAxiosParamCreator(configuration).getPerceptionpdf(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retorna la respuesta de SUNAT y el XML firmado
         * @summary Enviar un Comprobante de Percepcion
         * @param {Perception} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendPerception(body: Perception, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DocumentResponse>>> {
            const localVarAxiosArgs = await PerceptionApiAxiosParamCreator(configuration).sendPerception(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * PerceptionApi - factory interface
 * @export
 */
export const PerceptionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Retorna el XML
         * @summary Generar el XML de un Comprobante de Percepcion
         * @param {Perception} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPerceptionXml(body: Perception, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return PerceptionApiFp(configuration).getPerceptionXml(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna el pdf
         * @summary Generar el pdf de un Comprobante de Percepcion
         * @param {Perception} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPerceptionpdf(body: Perception, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return PerceptionApiFp(configuration).getPerceptionpdf(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna la respuesta de SUNAT y el XML firmado
         * @summary Enviar un Comprobante de Percepcion
         * @param {Perception} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendPerception(body: Perception, options?: AxiosRequestConfig): Promise<AxiosResponse<DocumentResponse>> {
            return PerceptionApiFp(configuration).sendPerception(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PerceptionApi - object-oriented interface
 * @export
 * @class PerceptionApi
 * @extends {BaseAPI}
 */
export class PerceptionApi extends BaseAPI {
    /**
     * Retorna el XML
     * @summary Generar el XML de un Comprobante de Percepcion
     * @param {Perception} body Comprobante
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PerceptionApi
     */
    public async getPerceptionXml(body: Perception, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return PerceptionApiFp(this.configuration).getPerceptionXml(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retorna el pdf
     * @summary Generar el pdf de un Comprobante de Percepcion
     * @param {Perception} body Comprobante
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PerceptionApi
     */
    public async getPerceptionpdf(body: Perception, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return PerceptionApiFp(this.configuration).getPerceptionpdf(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retorna la respuesta de SUNAT y el XML firmado
     * @summary Enviar un Comprobante de Percepcion
     * @param {Perception} body Comprobante
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PerceptionApi
     */
    public async sendPerception(body: Perception, options?: AxiosRequestConfig) : Promise<AxiosResponse<DocumentResponse>> {
        return PerceptionApiFp(this.configuration).sendPerception(body, options).then((request) => request(this.axios, this.basePath));
    }
}
