/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { DocumentResponse } from '../models';
import { Retention } from '../models';
import { ValidationResponse } from '../models';
/**
 * RetentionApi - axios parameter creator
 * @export
 */
export const RetentionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retorna el XML
         * @summary Generar el XML de un Comprobante de Retencion
         * @param {Retention} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRetentionXml: async (body: Retention, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling getRetentionXml.');
            }
            const localVarPath = `/retention/xml`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna el pdf
         * @summary Generar el pdf de un Comprobante de Retencion
         * @param {Retention} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRetentionpdf: async (body: Retention, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling getRetentionpdf.');
            }
            const localVarPath = `/retention/pdf`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna la respuesta de SUNAT y el XML firmado
         * @summary Enviar un Comprobante de Retencion
         * @param {Retention} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendRetention: async (body: Retention, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling sendRetention.');
            }
            const localVarPath = `/retention/send`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RetentionApi - functional programming interface
 * @export
 */
export const RetentionApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retorna el XML
         * @summary Generar el XML de un Comprobante de Retencion
         * @param {Retention} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRetentionXml(body: Retention, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await RetentionApiAxiosParamCreator(configuration).getRetentionXml(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retorna el pdf
         * @summary Generar el pdf de un Comprobante de Retencion
         * @param {Retention} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRetentionpdf(body: Retention, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await RetentionApiAxiosParamCreator(configuration).getRetentionpdf(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retorna la respuesta de SUNAT y el XML firmado
         * @summary Enviar un Comprobante de Retencion
         * @param {Retention} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendRetention(body: Retention, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DocumentResponse>>> {
            const localVarAxiosArgs = await RetentionApiAxiosParamCreator(configuration).sendRetention(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * RetentionApi - factory interface
 * @export
 */
export const RetentionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Retorna el XML
         * @summary Generar el XML de un Comprobante de Retencion
         * @param {Retention} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRetentionXml(body: Retention, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return RetentionApiFp(configuration).getRetentionXml(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna el pdf
         * @summary Generar el pdf de un Comprobante de Retencion
         * @param {Retention} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRetentionpdf(body: Retention, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return RetentionApiFp(configuration).getRetentionpdf(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna la respuesta de SUNAT y el XML firmado
         * @summary Enviar un Comprobante de Retencion
         * @param {Retention} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendRetention(body: Retention, options?: AxiosRequestConfig): Promise<AxiosResponse<DocumentResponse>> {
            return RetentionApiFp(configuration).sendRetention(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RetentionApi - object-oriented interface
 * @export
 * @class RetentionApi
 * @extends {BaseAPI}
 */
export class RetentionApi extends BaseAPI {
    /**
     * Retorna el XML
     * @summary Generar el XML de un Comprobante de Retencion
     * @param {Retention} body Comprobante
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RetentionApi
     */
    public async getRetentionXml(body: Retention, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return RetentionApiFp(this.configuration).getRetentionXml(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retorna el pdf
     * @summary Generar el pdf de un Comprobante de Retencion
     * @param {Retention} body Comprobante
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RetentionApi
     */
    public async getRetentionpdf(body: Retention, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return RetentionApiFp(this.configuration).getRetentionpdf(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retorna la respuesta de SUNAT y el XML firmado
     * @summary Enviar un Comprobante de Retencion
     * @param {Retention} body Comprobante
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RetentionApi
     */
    public async sendRetention(body: Retention, options?: AxiosRequestConfig) : Promise<AxiosResponse<DocumentResponse>> {
        return RetentionApiFp(this.configuration).sendRetention(body, options).then((request) => request(this.axios, this.basePath));
    }
}
