/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { StatusResult } from '../models';
import { Summary } from '../models';
import { SummaryResponse } from '../models';
import { ValidationResponse } from '../models';
/**
 * SummaryApi - axios parameter creator
 * @export
 */
export const SummaryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retorna el PDF
         * @summary Generar el PDF de un resumen diario
         * @param {Summary} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSummaryPdf: async (body: Summary, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling getSummaryPdf.');
            }
            const localVarPath = `/summary/pdf`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna el XML
         * @summary Obtiene el estado del ticket
         * @param {string} [ticket] Ticket de Resumen diario
         * @param {string} [ruc] RUC de empresa (Multiples Empresas)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSummaryStatus: async (ticket?: string, ruc?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/summary/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            if (ticket !== undefined) {
                localVarQueryParameter['ticket'] = ticket;
            }

            if (ruc !== undefined) {
                localVarQueryParameter['ruc'] = ruc;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna el XML
         * @summary Generar el XML de un resumen diario
         * @param {Summary} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSummaryXml: async (body: Summary, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling getSummaryXml.');
            }
            const localVarPath = `/summary/xml`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna la respuesta de SUNAT y el XML firmado
         * @summary Enviar una Resumen diario de Boletas
         * @param {Summary} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendSummary: async (body: Summary, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling sendSummary.');
            }
            const localVarPath = `/summary/send`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SummaryApi - functional programming interface
 * @export
 */
export const SummaryApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retorna el PDF
         * @summary Generar el PDF de un resumen diario
         * @param {Summary} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSummaryPdf(body: Summary, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await SummaryApiAxiosParamCreator(configuration).getSummaryPdf(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retorna el XML
         * @summary Obtiene el estado del ticket
         * @param {string} [ticket] Ticket de Resumen diario
         * @param {string} [ruc] RUC de empresa (Multiples Empresas)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSummaryStatus(ticket?: string, ruc?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<StatusResult>>> {
            const localVarAxiosArgs = await SummaryApiAxiosParamCreator(configuration).getSummaryStatus(ticket, ruc, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retorna el XML
         * @summary Generar el XML de un resumen diario
         * @param {Summary} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSummaryXml(body: Summary, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await SummaryApiAxiosParamCreator(configuration).getSummaryXml(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retorna la respuesta de SUNAT y el XML firmado
         * @summary Enviar una Resumen diario de Boletas
         * @param {Summary} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendSummary(body: Summary, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<SummaryResponse>>> {
            const localVarAxiosArgs = await SummaryApiAxiosParamCreator(configuration).sendSummary(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SummaryApi - factory interface
 * @export
 */
export const SummaryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Retorna el PDF
         * @summary Generar el PDF de un resumen diario
         * @param {Summary} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSummaryPdf(body: Summary, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return SummaryApiFp(configuration).getSummaryPdf(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna el XML
         * @summary Obtiene el estado del ticket
         * @param {string} [ticket] Ticket de Resumen diario
         * @param {string} [ruc] RUC de empresa (Multiples Empresas)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSummaryStatus(ticket?: string, ruc?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StatusResult>> {
            return SummaryApiFp(configuration).getSummaryStatus(ticket, ruc, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna el XML
         * @summary Generar el XML de un resumen diario
         * @param {Summary} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSummaryXml(body: Summary, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return SummaryApiFp(configuration).getSummaryXml(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna la respuesta de SUNAT y el XML firmado
         * @summary Enviar una Resumen diario de Boletas
         * @param {Summary} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendSummary(body: Summary, options?: AxiosRequestConfig): Promise<AxiosResponse<SummaryResponse>> {
            return SummaryApiFp(configuration).sendSummary(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SummaryApi - object-oriented interface
 * @export
 * @class SummaryApi
 * @extends {BaseAPI}
 */
export class SummaryApi extends BaseAPI {
    /**
     * Retorna el PDF
     * @summary Generar el PDF de un resumen diario
     * @param {Summary} body Comprobante
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SummaryApi
     */
    public async getSummaryPdf(body: Summary, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return SummaryApiFp(this.configuration).getSummaryPdf(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retorna el XML
     * @summary Obtiene el estado del ticket
     * @param {string} [ticket] Ticket de Resumen diario
     * @param {string} [ruc] RUC de empresa (Multiples Empresas)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SummaryApi
     */
    public async getSummaryStatus(ticket?: string, ruc?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<StatusResult>> {
        return SummaryApiFp(this.configuration).getSummaryStatus(ticket, ruc, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retorna el XML
     * @summary Generar el XML de un resumen diario
     * @param {Summary} body Comprobante
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SummaryApi
     */
    public async getSummaryXml(body: Summary, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return SummaryApiFp(this.configuration).getSummaryXml(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retorna la respuesta de SUNAT y el XML firmado
     * @summary Enviar una Resumen diario de Boletas
     * @param {Summary} body Comprobante
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SummaryApi
     */
    public async sendSummary(body: Summary, options?: AxiosRequestConfig) : Promise<AxiosResponse<SummaryResponse>> {
        return SummaryApiFp(this.configuration).sendSummary(body, options).then((request) => request(this.axios, this.basePath));
    }
}
