/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Reversion } from '../models';
import { StatusResult } from '../models';
import { SummaryResponse } from '../models';
import { ValidationResponse } from '../models';
import { Voided } from '../models';
/**
 * VoidedApi - axios parameter creator
 * @export
 */
export const VoidedApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retorna el XML
         * @summary Obtiene el estado del ticket
         * @param {string} [ticket] Ticket de Resumen de Reversiones
         * @param {string} [ruc] RUC de empresa (Multiples Empresas)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReversionStatus: async (ticket?: string, ruc?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/reversion/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            if (ticket !== undefined) {
                localVarQueryParameter['ticket'] = ticket;
            }

            if (ruc !== undefined) {
                localVarQueryParameter['ruc'] = ruc;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna el XML
         * @summary Generar el XML de un Resumen de Reversiones
         * @param {Reversion} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReversionXml: async (body: Reversion, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling getReversionXml.');
            }
            const localVarPath = `/reversion/xml`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna el pdf
         * @summary Generar el pdf de un Resumen de Reversiones
         * @param {Reversion} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReversionpdf: async (body: Reversion, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling getReversionpdf.');
            }
            const localVarPath = `/reversion/pdf`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna el PDF
         * @summary Generar el PDF de una Comunicación de Bajas
         * @param {Voided} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVoidedPdf: async (body: Voided, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling getVoidedPdf.');
            }
            const localVarPath = `/voided/pdf`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna el XML
         * @summary Obtiene el estado del ticket
         * @param {string} [ticket] Ticket de Comunicación de baja
         * @param {string} [ruc] RUC de empresa (Multiples Empresas)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVoidedStatus: async (ticket?: string, ruc?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/voided/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            if (ticket !== undefined) {
                localVarQueryParameter['ticket'] = ticket;
            }

            if (ruc !== undefined) {
                localVarQueryParameter['ruc'] = ruc;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna el XML
         * @summary Generar el XML de una Comunicación de Bajas
         * @param {Voided} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVoidedXml: async (body: Voided, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling getVoidedXml.');
            }
            const localVarPath = `/voided/xml`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna la respuesta de SUNAT y el XML firmado
         * @summary Enviar una Comunicación de Bajas
         * @param {Voided} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendVoided: async (body: Voided, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling sendVoided.');
            }
            const localVarPath = `/voided/send`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("token")
                    : await configuration.apiKey;
                localVarQueryParameter["token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VoidedApi - functional programming interface
 * @export
 */
export const VoidedApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retorna el XML
         * @summary Obtiene el estado del ticket
         * @param {string} [ticket] Ticket de Resumen de Reversiones
         * @param {string} [ruc] RUC de empresa (Multiples Empresas)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReversionStatus(ticket?: string, ruc?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<StatusResult>>> {
            const localVarAxiosArgs = await VoidedApiAxiosParamCreator(configuration).getReversionStatus(ticket, ruc, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retorna el XML
         * @summary Generar el XML de un Resumen de Reversiones
         * @param {Reversion} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReversionXml(body: Reversion, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await VoidedApiAxiosParamCreator(configuration).getReversionXml(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retorna el pdf
         * @summary Generar el pdf de un Resumen de Reversiones
         * @param {Reversion} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReversionpdf(body: Reversion, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await VoidedApiAxiosParamCreator(configuration).getReversionpdf(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retorna el PDF
         * @summary Generar el PDF de una Comunicación de Bajas
         * @param {Voided} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVoidedPdf(body: Voided, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await VoidedApiAxiosParamCreator(configuration).getVoidedPdf(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retorna el XML
         * @summary Obtiene el estado del ticket
         * @param {string} [ticket] Ticket de Comunicación de baja
         * @param {string} [ruc] RUC de empresa (Multiples Empresas)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVoidedStatus(ticket?: string, ruc?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<StatusResult>>> {
            const localVarAxiosArgs = await VoidedApiAxiosParamCreator(configuration).getVoidedStatus(ticket, ruc, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retorna el XML
         * @summary Generar el XML de una Comunicación de Bajas
         * @param {Voided} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVoidedXml(body: Voided, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await VoidedApiAxiosParamCreator(configuration).getVoidedXml(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retorna la respuesta de SUNAT y el XML firmado
         * @summary Enviar una Comunicación de Bajas
         * @param {Voided} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendVoided(body: Voided, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<SummaryResponse>>> {
            const localVarAxiosArgs = await VoidedApiAxiosParamCreator(configuration).sendVoided(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * VoidedApi - factory interface
 * @export
 */
export const VoidedApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Retorna el XML
         * @summary Obtiene el estado del ticket
         * @param {string} [ticket] Ticket de Resumen de Reversiones
         * @param {string} [ruc] RUC de empresa (Multiples Empresas)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReversionStatus(ticket?: string, ruc?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StatusResult>> {
            return VoidedApiFp(configuration).getReversionStatus(ticket, ruc, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna el XML
         * @summary Generar el XML de un Resumen de Reversiones
         * @param {Reversion} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReversionXml(body: Reversion, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return VoidedApiFp(configuration).getReversionXml(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna el pdf
         * @summary Generar el pdf de un Resumen de Reversiones
         * @param {Reversion} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReversionpdf(body: Reversion, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return VoidedApiFp(configuration).getReversionpdf(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna el PDF
         * @summary Generar el PDF de una Comunicación de Bajas
         * @param {Voided} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVoidedPdf(body: Voided, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return VoidedApiFp(configuration).getVoidedPdf(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna el XML
         * @summary Obtiene el estado del ticket
         * @param {string} [ticket] Ticket de Comunicación de baja
         * @param {string} [ruc] RUC de empresa (Multiples Empresas)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVoidedStatus(ticket?: string, ruc?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StatusResult>> {
            return VoidedApiFp(configuration).getVoidedStatus(ticket, ruc, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna el XML
         * @summary Generar el XML de una Comunicación de Bajas
         * @param {Voided} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVoidedXml(body: Voided, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return VoidedApiFp(configuration).getVoidedXml(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna la respuesta de SUNAT y el XML firmado
         * @summary Enviar una Comunicación de Bajas
         * @param {Voided} body Comprobante
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendVoided(body: Voided, options?: AxiosRequestConfig): Promise<AxiosResponse<SummaryResponse>> {
            return VoidedApiFp(configuration).sendVoided(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VoidedApi - object-oriented interface
 * @export
 * @class VoidedApi
 * @extends {BaseAPI}
 */
export class VoidedApi extends BaseAPI {
    /**
     * Retorna el XML
     * @summary Obtiene el estado del ticket
     * @param {string} [ticket] Ticket de Resumen de Reversiones
     * @param {string} [ruc] RUC de empresa (Multiples Empresas)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoidedApi
     */
    public async getReversionStatus(ticket?: string, ruc?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<StatusResult>> {
        return VoidedApiFp(this.configuration).getReversionStatus(ticket, ruc, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retorna el XML
     * @summary Generar el XML de un Resumen de Reversiones
     * @param {Reversion} body Comprobante
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoidedApi
     */
    public async getReversionXml(body: Reversion, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return VoidedApiFp(this.configuration).getReversionXml(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retorna el pdf
     * @summary Generar el pdf de un Resumen de Reversiones
     * @param {Reversion} body Comprobante
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoidedApi
     */
    public async getReversionpdf(body: Reversion, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return VoidedApiFp(this.configuration).getReversionpdf(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retorna el PDF
     * @summary Generar el PDF de una Comunicación de Bajas
     * @param {Voided} body Comprobante
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoidedApi
     */
    public async getVoidedPdf(body: Voided, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return VoidedApiFp(this.configuration).getVoidedPdf(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retorna el XML
     * @summary Obtiene el estado del ticket
     * @param {string} [ticket] Ticket de Comunicación de baja
     * @param {string} [ruc] RUC de empresa (Multiples Empresas)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoidedApi
     */
    public async getVoidedStatus(ticket?: string, ruc?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<StatusResult>> {
        return VoidedApiFp(this.configuration).getVoidedStatus(ticket, ruc, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retorna el XML
     * @summary Generar el XML de una Comunicación de Bajas
     * @param {Voided} body Comprobante
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoidedApi
     */
    public async getVoidedXml(body: Voided, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return VoidedApiFp(this.configuration).getVoidedXml(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retorna la respuesta de SUNAT y el XML firmado
     * @summary Enviar una Comunicación de Bajas
     * @param {Voided} body Comprobante
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoidedApi
     */
    public async sendVoided(body: Voided, options?: AxiosRequestConfig) : Promise<AxiosResponse<SummaryResponse>> {
        return VoidedApiFp(this.configuration).sendVoided(body, options).then((request) => request(this.axios, this.basePath));
    }
}
