/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AdditionalDoc
 */
export interface AdditionalDoc {

    /**
     * @type {string}
     * @memberof AdditionalDoc
     */
    tipoDesc?: string;

    /**
     * @type {string}
     * @memberof AdditionalDoc
     */
    tipo?: string;

    /**
     * @type {string}
     * @memberof AdditionalDoc
     */
    nro?: string;

    /**
     * @type {string}
     * @memberof AdditionalDoc
     */
    emisor?: string;
}
