/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Address
 */
export interface Address {

    /**
     * @type {string}
     * @memberof Address
     */
    ubigueo?: string;

    /**
     * @type {string}
     * @memberof Address
     */
    codigoPais?: string;

    /**
     * @type {string}
     * @memberof Address
     */
    departamento?: string;

    /**
     * @type {string}
     * @memberof Address
     */
    provincia?: string;

    /**
     * @type {string}
     * @memberof Address
     */
    distrito?: string;

    /**
     * @type {string}
     * @memberof Address
     */
    urbanizacion?: string;

    /**
     * @type {string}
     * @memberof Address
     */
    direccion?: string;

    /**
     * @type {string}
     * @memberof Address
     */
    codLocal?: string;
}
