/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CdrResponse
 */
export interface CdrResponse {

    /**
     * @type {boolean}
     * @memberof CdrResponse
     */
    accepted?: boolean;

    /**
     * @type {string}
     * @memberof CdrResponse
     */
    id?: string;

    /**
     * @type {string}
     * @memberof CdrResponse
     */
    code?: string;

    /**
     * @type {string}
     * @memberof CdrResponse
     */
    description?: string;

    /**
     * @type {Array<string>}
     * @memberof CdrResponse
     */
    notes?: Array<string>;
}
