/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Charge
 */
export interface Charge {

    /**
     * @type {string}
     * @memberof Charge
     */
    codTipo?: string;

    /**
     * @type {string}
     * @memberof Charge
     */
    factor?: string;

    /**
     * @type {number}
     * @memberof Charge
     */
    monto?: number;

    /**
     * @type {number}
     * @memberof Charge
     */
    montoBase?: number;
}
