/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Address } from './address';
 /**
 * 
 *
 * @export
 * @interface Client
 */
export interface Client {

    /**
     * @type {string}
     * @memberof Client
     */
    tipoDoc?: string;

    /**
     * @type {string}
     * @memberof Client
     */
    numDoc?: string;

    /**
     * @type {string}
     * @memberof Client
     */
    rznSocial?: string;

    /**
     * @type {Address}
     * @memberof Client
     */
    address?: Address;

    /**
     * @type {string}
     * @memberof Client
     */
    email?: string;

    /**
     * @type {string}
     * @memberof Client
     */
    telephone?: string;
}
