/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Address } from './address';
 /**
 * 
 *
 * @export
 * @interface Company
 */
export interface Company {

    /**
     * @type {string}
     * @memberof Company
     */
    ruc?: string;

    /**
     * @type {string}
     * @memberof Company
     */
    razonSocial?: string;

    /**
     * @type {string}
     * @memberof Company
     */
    nombreComercial?: string;

    /**
     * @type {Address}
     * @memberof Company
     */
    address?: Address;

    /**
     * @type {string}
     * @memberof Company
     */
    email?: string;

    /**
     * @type {string}
     * @memberof Company
     */
    telephone?: string;
}
