/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DetailAttribute } from './detail-attribute';
 /**
 * 
 *
 * @export
 * @interface DespatchDetail
 */
export interface DespatchDetail {

    /**
     * @type {string}
     * @memberof DespatchDetail
     */
    codigo?: string;

    /**
     * @type {string}
     * @memberof DespatchDetail
     */
    descripcion?: string;

    /**
     * @type {string}
     * @memberof DespatchDetail
     */
    unidad?: string;

    /**
     * @type {number}
     * @memberof DespatchDetail
     */
    cantidad?: number;

    /**
     * @type {string}
     * @memberof DespatchDetail
     */
    codProdSunat?: string;

    /**
     * @type {Array<DetailAttribute>}
     * @memberof DespatchDetail
     */
    atributos?: Array<DetailAttribute>;
}
