/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AdditionalDoc } from './additional-doc';
import { Client } from './client';
import { Company } from './company';
import { DespatchDetail } from './despatch-detail';
import { Shipment } from './shipment';
 /**
 * 
 *
 * @export
 * @interface Despatch
 */
export interface Despatch {

    /**
     * @type {string}
     * @memberof Despatch
     */
    version?: string;

    /**
     * @type {string}
     * @memberof Despatch
     */
    tipoDoc?: string;

    /**
     * @type {string}
     * @memberof Despatch
     */
    serie?: string;

    /**
     * @type {string}
     * @memberof Despatch
     */
    correlativo?: string;

    /**
     * @type {string}
     * @memberof Despatch
     */
    observacion?: string;

    /**
     * @type {Date}
     * @memberof Despatch
     */
    fechaEmision?: Date;

    /**
     * @type {Company}
     * @memberof Despatch
     */
    company?: Company;

    /**
     * @type {Client}
     * @memberof Despatch
     */
    destinatario?: Client;

    /**
     * @type {Client}
     * @memberof Despatch
     */
    tercero?: Client;

    /**
     * @type {Client}
     * @memberof Despatch
     */
    comprador?: Client;

    /**
     * @type {Shipment}
     * @memberof Despatch
     */
    envio?: Shipment;

    /**
     * @type {Array<AdditionalDoc>}
     * @memberof Despatch
     */
    addDocs?: Array<AdditionalDoc>;

    /**
     * @type {Array<DespatchDetail>}
     * @memberof Despatch
     */
    details?: Array<DespatchDetail>;

    /**
     * @type {string}
     * @memberof Despatch
     */
    name?: string;
}
