/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Document
 */
export interface Document {

    /**
     * @type {string}
     * @memberof Document
     */
    tipoDoc?: string;

    /**
     * @type {string}
     * @memberof Document
     */
    nroDoc?: string;
}
