/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Driver
 */
export interface Driver {

    /**
     * @type {string}
     * @memberof Driver
     */
    tipo?: string;

    /**
     * @type {string}
     * @memberof Driver
     */
    tipoDoc?: string;

    /**
     * @type {string}
     * @memberof Driver
     */
    nroDoc?: string;

    /**
     * @type {string}
     * @memberof Driver
     */
    nombres?: string;

    /**
     * @type {string}
     * @memberof Driver
     */
    apellidos?: string;

    /**
     * @type {string}
     * @memberof Driver
     */
    licencia?: string;
}
