/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Client } from './client';
import { Direction } from './direction';
 /**
 * 
 *
 * @export
 * @interface EmbededDespatch
 */
export interface EmbededDespatch {

    /**
     * @type {Direction}
     * @memberof EmbededDespatch
     */
    llegada?: Direction;

    /**
     * @type {Direction}
     * @memberof EmbededDespatch
     */
    partida?: Direction;

    /**
     * @type {Client}
     * @memberof EmbededDespatch
     */
    transportista?: Client;

    /**
     * @type {string}
     * @memberof EmbededDespatch
     */
    nroLicencia?: string;

    /**
     * @type {string}
     * @memberof EmbededDespatch
     */
    transpPlaca?: string;

    /**
     * @type {string}
     * @memberof EmbededDespatch
     */
    transpCodeAuth?: string;

    /**
     * @type {string}
     * @memberof EmbededDespatch
     */
    transpMarca?: string;

    /**
     * @type {string}
     * @memberof EmbededDespatch
     */
    modTraslado?: string;

    /**
     * @type {number}
     * @memberof EmbededDespatch
     */
    pesoBruto?: number;

    /**
     * @type {string}
     * @memberof EmbededDespatch
     */
    undPesoBruto?: string;
}
