/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Exchange
 */
export interface Exchange {

    /**
     * @type {string}
     * @memberof Exchange
     */
    monedaRef?: string;

    /**
     * @type {string}
     * @memberof Exchange
     */
    monedaObj?: string;

    /**
     * @type {number}
     * @memberof Exchange
     */
    factor?: number;

    /**
     * @type {Date}
     * @memberof Exchange
     */
    fecha?: Date;
}
