/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FilesData
 */
export interface FilesData {

    /**
     * certificado PEM en formato base64
     *
     * @type {string}
     * @memberof FilesData
     */
    certificate?: string;

    /**
     * logo png en formato base64
     *
     * @type {string}
     * @memberof FilesData
     */
    logo?: string;
}
