/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Address } from './address';
import { Charge } from './charge';
import { Client } from './client';
import { Company } from './company';
import { Cuota } from './cuota';
import { Detraction } from './detraction';
import { Document } from './document';
import { EmbededDespatch } from './embeded-despatch';
import { Legend } from './legend';
import { PaymentTerms } from './payment-terms';
import { Prepayment } from './prepayment';
import { SaleDetail } from './sale-detail';
import { SalePerception } from './sale-perception';
 /**
 * 
 *
 * @export
 * @interface Invoice
 */
export interface Invoice {

    /**
     * @type {string}
     * @memberof Invoice
     */
    tipoDoc?: string;

    /**
     * @type {string}
     * @memberof Invoice
     */
    serie?: string;

    /**
     * @type {string}
     * @memberof Invoice
     */
    correlativo?: string;

    /**
     * @type {Date}
     * @memberof Invoice
     */
    fechaEmision?: Date;

    /**
     * @type {PaymentTerms}
     * @memberof Invoice
     */
    formaPago?: PaymentTerms;

    /**
     * @type {Array<Cuota>}
     * @memberof Invoice
     */
    cuotas?: Array<Cuota>;

    /**
     * @type {Client}
     * @memberof Invoice
     */
    client?: Client;

    /**
     * @type {Company}
     * @memberof Invoice
     */
    company?: Company;

    /**
     * @type {string}
     * @memberof Invoice
     */
    tipoMoneda?: string;

    /**
     * @type {number}
     * @memberof Invoice
     */
    sumOtrosCargos?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    mtoOperGravadas?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    mtoOperInafectas?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    mtoOperExoneradas?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    mtoOperExportacion?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    mtoIGV?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    mtoIGVGratuitas?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    mtoISC?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    mtoOtrosTributos?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    icbper?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    valorVenta?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    subTotal?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    mtoImpVenta?: number;

    /**
     * @type {Array<SaleDetail>}
     * @memberof Invoice
     */
    details?: Array<SaleDetail>;

    /**
     * @type {Array<Legend>}
     * @memberof Invoice
     */
    legends?: Array<Legend>;

    /**
     * @type {Array<Document>}
     * @memberof Invoice
     */
    guias?: Array<Document>;

    /**
     * @type {Array<Document>}
     * @memberof Invoice
     */
    relDocs?: Array<Document>;

    /**
     * @type {string}
     * @memberof Invoice
     */
    observacion?: string;

    /**
     * @type {string}
     * @memberof Invoice
     */
    compra?: string;

    /**
     * @type {number}
     * @memberof Invoice
     */
    mtoBaseIsc?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    mtoBaseOth?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    totalImpuestos?: number;

    /**
     * @type {string}
     * @memberof Invoice
     */
    ublVersion?: string;

    /**
     * @type {string}
     * @memberof Invoice
     */
    tipoOperacion?: string;

    /**
     * @type {Date}
     * @memberof Invoice
     */
    fecVencimiento?: Date;

    /**
     * @type {number}
     * @memberof Invoice
     */
    sumDsctoGlobal?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    mtoDescuentos?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    mtoOperGratuitas?: number;

    /**
     * @type {number}
     * @memberof Invoice
     */
    totalAnticipos?: number;

    /**
     * @type {SalePerception}
     * @memberof Invoice
     */
    perception?: SalePerception;

    /**
     * @type {EmbededDespatch}
     * @memberof Invoice
     */
    guiaEmbebida?: EmbededDespatch;

    /**
     * @type {Array<Prepayment>}
     * @memberof Invoice
     */
    anticipos?: Array<Prepayment>;

    /**
     * @type {Detraction}
     * @memberof Invoice
     */
    detraccion?: Detraction;

    /**
     * @type {Client}
     * @memberof Invoice
     */
    seller?: Client;

    /**
     * @type {Address}
     * @memberof Invoice
     */
    direccionEntrega?: Address;

    /**
     * @type {Array<Charge>}
     * @memberof Invoice
     */
    descuentos?: Array<Charge>;

    /**
     * @type {Array<Charge>}
     * @memberof Invoice
     */
    cargos?: Array<Charge>;

    /**
     * @type {number}
     * @memberof Invoice
     */
    mtoCargos?: number;
}
