/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PaymentTerms
 */
export interface PaymentTerms {

    /**
     * @type {string}
     * @memberof PaymentTerms
     */
    moneda?: string;

    /**
     * @type {string}
     * @memberof PaymentTerms
     */
    tipo?: string;

    /**
     * @type {number}
     * @memberof PaymentTerms
     */
    monto?: number;
}
