/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Payment
 */
export interface Payment {

    /**
     * @type {string}
     * @memberof Payment
     */
    moneda?: string;

    /**
     * @type {number}
     * @memberof Payment
     */
    importe?: number;

    /**
     * @type {Date}
     * @memberof Payment
     */
    fecha?: Date;
}
