/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Client } from './client';
import { Company } from './company';
import { PerceptionDetail } from './perception-detail';
 /**
 * 
 *
 * @export
 * @interface Perception
 */
export interface Perception {

    /**
     * @type {string}
     * @memberof Perception
     */
    serie?: string;

    /**
     * @type {string}
     * @memberof Perception
     */
    correlativo?: string;

    /**
     * @type {Date}
     * @memberof Perception
     */
    fechaEmision?: Date;

    /**
     * @type {Company}
     * @memberof Perception
     */
    company?: Company;

    /**
     * @type {Client}
     * @memberof Perception
     */
    proveedor?: Client;

    /**
     * @type {string}
     * @memberof Perception
     */
    regimen?: string;

    /**
     * @type {number}
     * @memberof Perception
     */
    tasa?: number;

    /**
     * @type {number}
     * @memberof Perception
     */
    impPercibido?: number;

    /**
     * @type {number}
     * @memberof Perception
     */
    impCobrado?: number;

    /**
     * @type {string}
     * @memberof Perception
     */
    observacion?: string;

    /**
     * @type {Array<PerceptionDetail>}
     * @memberof Perception
     */
    details?: Array<PerceptionDetail>;
}
