/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Exchange } from './exchange';
import { Payment } from './payment';
 /**
 * 
 *
 * @export
 * @interface RetentionDetail
 */
export interface RetentionDetail {

    /**
     * @type {string}
     * @memberof RetentionDetail
     */
    tipoDoc?: string;

    /**
     * @type {string}
     * @memberof RetentionDetail
     */
    numDoc?: string;

    /**
     * @type {Date}
     * @memberof RetentionDetail
     */
    fechaEmision?: Date;

    /**
     * @type {number}
     * @memberof RetentionDetail
     */
    impTotal?: number;

    /**
     * @type {string}
     * @memberof RetentionDetail
     */
    moneda?: string;

    /**
     * @type {Array<Payment>}
     * @memberof RetentionDetail
     */
    pagos?: Array<Payment>;

    /**
     * @type {Date}
     * @memberof RetentionDetail
     */
    fechaRetencion?: Date;

    /**
     * @type {number}
     * @memberof RetentionDetail
     */
    impRetenido?: number;

    /**
     * @type {number}
     * @memberof RetentionDetail
     */
    impPagar?: number;

    /**
     * @type {Exchange}
     * @memberof RetentionDetail
     */
    tipoCambio?: Exchange;
}
