/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Charge } from './charge';
import { DetailAttribute } from './detail-attribute';
 /**
 * 
 *
 * @export
 * @interface SaleDetail
 */
export interface SaleDetail {

    /**
     * @type {string}
     * @memberof SaleDetail
     */
    unidad?: string;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    cantidad?: number;

    /**
     * @type {string}
     * @memberof SaleDetail
     */
    codProducto?: string;

    /**
     * @type {string}
     * @memberof SaleDetail
     */
    codProdSunat?: string;

    /**
     * @type {string}
     * @memberof SaleDetail
     */
    codProdGS1?: string;

    /**
     * @type {string}
     * @memberof SaleDetail
     */
    descripcion?: string;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    mtoValorUnitario?: number;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    descuento?: number;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    igv?: number;

    /**
     * @type {string}
     * @memberof SaleDetail
     */
    tipAfeIgv?: string;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    isc?: number;

    /**
     * @type {string}
     * @memberof SaleDetail
     */
    tipSisIsc?: string;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    totalImpuestos?: number;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    mtoPrecioUnitario?: number;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    mtoValorVenta?: number;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    mtoValorGratuito?: number;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    mtoBaseIgv?: number;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    porcentajeIgv?: number;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    mtoBaseIsc?: number;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    porcentajeIsc?: number;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    mtoBaseOth?: number;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    porcentajeOth?: number;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    otroTributo?: number;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    icbper?: number;

    /**
     * @type {number}
     * @memberof SaleDetail
     */
    factorIcbper?: number;

    /**
     * @type {Array<Charge>}
     * @memberof SaleDetail
     */
    cargos?: Array<Charge>;

    /**
     * @type {Array<Charge>}
     * @memberof SaleDetail
     */
    descuentos?: Array<Charge>;

    /**
     * @type {Array<DetailAttribute>}
     * @memberof SaleDetail
     */
    atributos?: Array<DetailAttribute>;
}
