/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Direction } from './direction';
import { Driver } from './driver';
import { Puerto } from './puerto';
import { Transportist } from './transportist';
import { Vehicle } from './vehicle';
 /**
 * 
 *
 * @export
 * @interface Shipment
 */
export interface Shipment {

    /**
     * @type {string}
     * @memberof Shipment
     */
    codTraslado?: string;

    /**
     * @type {string}
     * @memberof Shipment
     */
    desTraslado?: string;

    /**
     * @type {string}
     * @memberof Shipment
     */
    sustentoPeso?: string;

    /**
     * @type {boolean}
     * @memberof Shipment
     */
    indTransbordo?: boolean;

    /**
     * @type {Array<string>}
     * @memberof Shipment
     */
    indicadores?: Array<string>;

    /**
     * @type {number}
     * @memberof Shipment
     */
    pesoItems?: number;

    /**
     * @type {number}
     * @memberof Shipment
     */
    pesoTotal?: number;

    /**
     * @type {string}
     * @memberof Shipment
     */
    undPesoTotal?: string;

    /**
     * @type {number}
     * @memberof Shipment
     */
    numBultos?: number;

    /**
     * @type {string}
     * @memberof Shipment
     */
    modTraslado?: string;

    /**
     * @type {Date}
     * @memberof Shipment
     */
    fecTraslado?: Date;

    /**
     * @type {string}
     * @memberof Shipment
     */
    numContenedor?: string;

    /**
     * @type {Array<string>}
     * @memberof Shipment
     */
    contenedores?: Array<string>;

    /**
     * @type {string}
     * @memberof Shipment
     */
    codPuerto?: string;

    /**
     * @type {Puerto}
     * @memberof Shipment
     */
    puerto?: Puerto;

    /**
     * @type {Puerto}
     * @memberof Shipment
     */
    aeropuerto?: Puerto;

    /**
     * @type {Transportist}
     * @memberof Shipment
     */
    transportista?: Transportist;

    /**
     * @type {Vehicle}
     * @memberof Shipment
     */
    vehiculo?: Vehicle;

    /**
     * @type {Array<Driver>}
     * @memberof Shipment
     */
    choferes?: Array<Driver>;

    /**
     * @type {Direction}
     * @memberof Shipment
     */
    llegada?: Direction;

    /**
     * @type {Direction}
     * @memberof Shipment
     */
    partida?: Direction;
}
