/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SummaryPerception
 */
export interface SummaryPerception {

    /**
     * @type {string}
     * @memberof SummaryPerception
     */
    codReg?: string;

    /**
     * @type {number}
     * @memberof SummaryPerception
     */
    tasa?: number;

    /**
     * @type {number}
     * @memberof SummaryPerception
     */
    mtoBase?: number;

    /**
     * @type {number}
     * @memberof SummaryPerception
     */
    mto?: number;

    /**
     * @type {number}
     * @memberof SummaryPerception
     */
    mtoTotal?: number;
}
