/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SummaryResult } from './summary-result';
 /**
 * 
 *
 * @export
 * @interface SummaryResponse
 */
export interface SummaryResponse {

    /**
     * @type {string}
     * @memberof SummaryResponse
     */
    xml?: string;

    /**
     * Resumen de la Firma Digital
     *
     * @type {string}
     * @memberof SummaryResponse
     */
    hash?: string;

    /**
     * @type {SummaryResult}
     * @memberof SummaryResponse
     */
    sunatResponse?: SummaryResult;
}
