/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Document } from './document';
import { SummaryPerception } from './summary-perception';
 /**
 * 
 *
 * @export
 * @interface SummaryDetail
 */
export interface SummaryDetail {

    /**
     * @type {string}
     * @memberof SummaryDetail
     */
    tipoDoc?: string;

    /**
     * @type {string}
     * @memberof SummaryDetail
     */
    serieNro?: string;

    /**
     * @type {string}
     * @memberof SummaryDetail
     */
    clienteTipo?: string;

    /**
     * @type {string}
     * @memberof SummaryDetail
     */
    clienteNro?: string;

    /**
     * @type {Document}
     * @memberof SummaryDetail
     */
    docReferencia?: Document;

    /**
     * @type {SummaryPerception}
     * @memberof SummaryDetail
     */
    percepcion?: SummaryPerception;

    /**
     * @type {string}
     * @memberof SummaryDetail
     */
    estado?: string;

    /**
     * @type {number}
     * @memberof SummaryDetail
     */
    total?: number;

    /**
     * @type {number}
     * @memberof SummaryDetail
     */
    mtoOperGravadas?: number;

    /**
     * @type {number}
     * @memberof SummaryDetail
     */
    mtoOperInafectas?: number;

    /**
     * @type {number}
     * @memberof SummaryDetail
     */
    mtoOperExoneradas?: number;

    /**
     * @type {number}
     * @memberof SummaryDetail
     */
    mtoOperExportacion?: number;

    /**
     * @type {number}
     * @memberof SummaryDetail
     */
    mtoOperGratuitas?: number;

    /**
     * @type {number}
     * @memberof SummaryDetail
     */
    mtoOtrosCargos?: number;

    /**
     * @type {number}
     * @memberof SummaryDetail
     */
    mtoIGV?: number;

    /**
     * @type {number}
     * @memberof SummaryDetail
     */
    mtoIvap?: number;

    /**
     * @type {number}
     * @memberof SummaryDetail
     */
    mtoIcbper?: number;

    /**
     * @type {number}
     * @memberof SummaryDetail
     */
    mtoISC?: number;

    /**
     * @type {number}
     * @memberof SummaryDetail
     */
    mtoOtrosTributos?: number;
}
