/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Company } from './company';
import { SummaryDetail } from './summary-detail';
 /**
 * 
 *
 * @export
 * @interface Summary
 */
export interface Summary {

    /**
     * @type {string}
     * @memberof Summary
     */
    correlativo?: string;

    /**
     * @type {Date}
     * @memberof Summary
     */
    fecGeneracion?: Date;

    /**
     * @type {Date}
     * @memberof Summary
     */
    fecResumen?: Date;

    /**
     * @type {string}
     * @memberof Summary
     */
    moneda?: string;

    /**
     * @type {Company}
     * @memberof Summary
     */
    company?: Company;

    /**
     * @type {Array<SummaryDetail>}
     * @memberof Summary
     */
    details?: Array<SummaryDetail>;
}
