/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Transportist
 */
export interface Transportist {

    /**
     * @type {string}
     * @memberof Transportist
     */
    tipoDoc?: string;

    /**
     * @type {string}
     * @memberof Transportist
     */
    numDoc?: string;

    /**
     * @type {string}
     * @memberof Transportist
     */
    rznSocial?: string;

    /**
     * @type {string}
     * @memberof Transportist
     */
    nroMtc?: string;

    /**
     * @type {string}
     * @memberof Transportist
     */
    placa?: string;

    /**
     * @type {string}
     * @memberof Transportist
     */
    choferTipoDoc?: string;

    /**
     * @type {string}
     * @memberof Transportist
     */
    choferDoc?: string;
}
