/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ValidationResponse
 */
export interface ValidationResponse {

    /**
     * @type {string}
     * @memberof ValidationResponse
     */
    message?: string;

    /**
     * @type {string}
     * @memberof ValidationResponse
     */
    field?: string;
}
