/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
* 
*
* @export
* @interface Vehicle
*/
export interface Vehicle {

    /**
     * @type {string}
     * @memberof Vehicle
     */
    placa?: string;

    /**
     * @type {string}
     * @memberof Vehicle
     */
    nroCirculacion?: string;

    /**
     * @type {string}
     * @memberof Vehicle
     */
    codEmisor?: string;

    /**
     * @type {string}
     * @memberof Vehicle
     */
    nroAutorizacion?: string;

    /**
     * @type {Array<Vehicle>}
     * @memberof Vehicle
     */
    secundarios?: Array<Vehicle>;
}
