/* tslint:disable */
/* eslint-disable */
/**
 * Lycet API
 * API REST basado en Greenter - Facturación Electrónica.
 *
 * OpenAPI spec version: 1.3
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Company } from './company';
import { VoidedDetail } from './voided-detail';
 /**
 * 
 *
 * @export
 * @interface Voided
 */
export interface Voided {

    /**
     * @type {string}
     * @memberof Voided
     */
    correlativo?: string;

    /**
     * @type {Date}
     * @memberof Voided
     */
    fecGeneracion?: Date;

    /**
     * @type {Date}
     * @memberof Voided
     */
    fecComunicacion?: Date;

    /**
     * @type {Company}
     * @memberof Voided
     */
    company?: Company;

    /**
     * @type {Array<VoidedDetail>}
     * @memberof Voided
     */
    details?: Array<VoidedDetail>;
}
